name=input("Enter your name :")
age=int(input("Enter your age :"))
school=input("Enter your school name :")
grade=int(input("Enter your grade :"))
print ("\n-------STUDENT PROFILE-------")
print (f"Name : {name}")
print (f"Age : {age}")    
print (f"School : {school}")
print (f"Grade : {grade}")